SELECT * FROM BOOK;

DESC BOOK;

SELECT COUNT(DISTINCT PUBLISHER)
    FROM BOOK;

SELECT PUBLISHER, COUNT(*)
    FROM BOOK
GROUP BY PUBLISHER;

SELECT BOOKNAME, PUBLISHER
    FROM BOOK
    WHERE BOOKNAME LIKE '%축구%';
    
SELECT * 
    FROM ORDERS;
-- 박지성이 산 책의 권수
SELECT C.NAME, COUNT(*)
    FROM CUSTOMER C ,ORDERS O
    WHERE C.CUSTID = O.CUSTID
    AND C.NAME = '박지성'
    GROUP BY C.NAME;
    
-- 박지성이 책에 쓴 돈은?
SELECT C.NAME, SUM(O.SALEPRICE)
    FROM CUSTOMER C ,ORDERS O
    WHERE C.CUSTID = O.CUSTID
    AND C.NAME = '박지성'
    GROUP BY C.NAME;
    
SELECT B.BOOKNAME, B.PUBLISHER
    FROM CUSTOMER C ,ORDERS O, BOOK B
    WHERE C.CUSTID = O.CUSTID
    AND O.BOOKID = B.BOOKID
    AND C.NAME = '박지성';
    
SELECT BOOKNAME, B.PUBLISHER
    FROM ORDERS O JOIN CUSTOMER C USING(CUSTID)
        JOIN BOOK B USING (BOOKID)  
    WHERE C.NAME = '박지성';
    
--7/4~7/7 사이에 주문 도서의 북 아이디
SELECT BOOKID
    FROM ORDERS
    WHERE ORDERDATE BETWEEN TO_DATE('14/07/04','YY/MM/DD') AND TO_DATE('14/07/07','YY/MM/DD');

--7/4~7/7 사이에 주문 도서의 북 이름
SELECT ORDERDATE, BOOKNAME
    FROM ORDERS O NATURAL JOIN BOOK B
    WHERE ORDERDATE BETWEEN TO_DATE('14/07/04','YY/MM/DD') AND TO_DATE('14/07/07','YY/MM/DD');
