SELECT * FROM BOOK;

--도서번호 1번 이름
SELECT BOOKNAME
    FROM BOOK
WHERE BOOKID = 1;

-- 가격이 2만원 이상인 제품
SELECT BOOKNAME FROM BOOK
    WHERE PRICE >= 20000;
    
-- 박지성이 주문한 책의 이름
--SELECT BOOKNAME FROM BOOK B JOIN CUSTOMER C USING 

SELECT BOOKNAME FROM ORDERS O
    JOIN CUSTOMER C USING (CUSTID)
    JOIN BOOK B USING (BOOKID)
    WHERE C.NAME = '박지성';
    
SELECT B.BOOKNAME 
    FROM ORDERS O, CUSTOMER C, BOOK B
    WHERE O.CUSTID = C.CUSTID
    AND O.BOOKID = B.BOOKID
    AND C.NAME = '박지성';

DROP TABLE BONUS;
DROP TABLE EMP;
DROP TABLE SALGRADE;

