SELECT * FROM TAB;

SELECT * FROM EMP; 

--DEPTNO를 중복 없이 출력
SELECT DISTINCT DEPTNO FROM EMP;

--연봉을(COMM 포함) SAL_YEAR 별칭으로
SELECT ENAME, SAL*12+COMM AS SAL_YEAR 
    FROM EMP;
    
--이름과 직책을 오름차순
SELECT ENAME, JOB 
    FROM EMP ORDER BY ENAME;

-- 이름과 직책 입사날짜를 입사날짜 내림차순
SELECT ENAME, JOB, HIREDATE
    FROM EMP ORDER BY HIREDATE;

SELECT ENAME, JOB, HIREDATE, DEPTNO 
    FROM EMP ORDER BY DEPTNO DESC, ENAME ASC;

-- 사원 이름 소문자, 첫자만 대문자로 바꾸기
SELECT ENAME, LOWER(ENAME), INITCAP(ENAME)
    FROM EMP;

-- 사원 이름 길이 구하기
SELECT ENAME, LENGTH(ENAME)
    FROM EMP;
    
-- 사원 이름 길이가 5 이상인 이름 구하기
SELECT ENAME, LENGTH(ENAME)
    FROM EMP
    WHERE LENGTH(ENAME) >=5;

-- LENGTH와 LENGTHB 차이 (LENGTHB는 바이트 수 계산)
SELECT LENGTH('한글'), LENGTHB('한글')
    FROM DUAL;
    
SELECT LENGTH('AB'), LENGTHB('AB')
    FROM DUAL;

SELECT 1+1 FROM DUAL;

-- 직책을 두번째 글짜부터 출력
SELECT JOB, SUBSTR(JOB, 2)
    FROM EMP;
    
-- 직책을 두번째 글짜부터 네번째 글짜까지 출력
SELECT JOB, SUBSTR(JOB, 2, 2)
    FROM EMP;

SELECT ENAME, SUBSTR(ENAME,3)
    FROM EMP;

-- 문자열에서 특정 문자의 위치(인덱스 넘버) 찾기
SELECT INSTR('HELLO, ORACLE!','L'), INSTR('HELLO, ORACLE!','L','5')
    FROM DUAL;
    
SELECT INSTR('HELLO, ORACLE!','L'), INSTR('HELLO, ORACLE!','L','5'), INSTR('HELLO, ORACLE!','L',1,2)
    FROM DUAL;

-- 문자 대체
SELECT REPLACE('010-3333-5555','-','/')
    FROM DUAL;
    
SELECT REPLACE('010-3333-5555','-')
    FROM DUAL;
    
-- 문자열 길이 지정 후 L/R 정렬
SELECT 'ORACLE', 
        LPAD('ORACLE',20),
        RPAD('ORCALE',20),
        LPAD('ORACLE',10,'#'),
        RPAD('ORCALE',10,'*')
    FROM DUAL;

-- CONCATENATE
SELECT CONCAT(EMPNO, ENAME) NO_NAME
    FROM EMP;
    
SELECT CONCAT(CONCAT(EMPNO, ':'), ENAME) NO_NAME
    FROM EMP;

--CONCATENATE를 ||로 표현    
SELECT EMPNO || ':' || ENAME
    FROM EMP;

-- 반올림
SELECT 1234.5678, ROUND(1234.5678, 2)
FROM DUAL;


SELECT 1234.5678, CEIL(1234.5678), FLOOR(1234.5678),
    MOD(11,2), TRUNC(1234.5678,2)
FROM DUAL;

SELECT CEIL(3.14), FLOOR(3.14), CEIL(-3.14), FLOOR(-3.14)
    FROM DUAL;

--오늘의 날짜
SELECT SYSDATE  FROM DUAL;

SELECT SYSDATE+1 FROM DUAL;

SELECT SYSDATE+10 FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 1)
    FROM DUAL;
    
SELECT ENAME, HIREDATE, ADD_MONTHS(HIREDATE,120)
    FROM EMP;
    
SELECT ROUND(MONTHS_BETWEEN(SYSDATE,HIREDATE)) AS MONTH_BETWEEN
    FROM EMP;

SELECT ROUND(SYSDATE,'CC') AS CC, 
    ROUND(SYSDATE,'YYYY') AS YYYY,
    ROUND(SYSDATE,'HH') AS HH
    FROM EMP;

SELECT EMPNO + '500'
    FROM EMP
WHERE ENAME = 'SCOTT';

SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH24:MI:SS') AS A
    FROM DUAL;
    
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') AS RRRR
    FROM DUAL;
    
SELECT TO_NUMBER('1300'-'500')
    FROM DUAL;

SELECT TO_NUMBER('1,300','99,999') - TO_NUMBER('1,500','99,999')
    FROM DUAL;
    
SELECT TO_DATE('2018%07%14','YYYY%MM%DD')
    FROM DUAL;
    
-- 왜 안되냐
SELECT TO_CHAR(TO_DATE('2023-12-25','YYYY-MM-DD'),'YYYY-MM-DD')
    FROM DUAL;
    
SELECT ROUND(TO_DATE('2023-12-25', 'YYYY-MM-DD')-SYSDATE)
FROM DUAL; 

SELECT * FROM EMP
WHERE HIREDATE > TO_DATE('1982-06-01','YYYY-MM-DD');

SELECT ENAME,COMM,NVL(COMM,0)
    FROM EMP;

SELECT ENAME,COMM,NVL(COMM,0),SAL*12+NVL(COMM,0) AS SAL12
    FROM EMP;
    
SELECT ENAME,COMM,NVL2(COMM,'O','X') 커미션유무
    FROM EMP;

SELECT ENAME, SAL*12 + NVL2(COMM, COMM,0)AS 연봉
    FROM EMP;
    
SELECT ENAME, JOB, SAL, 
    CASE
        WHEN SAL>900 THEN 'RICH'
        ELSE 'FOOL'
    END
    FROM EMP;

--예제    
SELECT EMPNO, ENAME, 
    TRUNC(SAL/21.5,2) AS DAY_PAY, ROUND(SAL/21.5/8,1) AS TIME_PAY
    FROM EMP;
-- 예제
SELECT EMPNO, ENAME, MGR, 
    CASE
        WHEN NVL(MGR,0) = 0 THEN 0000
        WHEN SUBSTR(TO_CHAR(MGR),1,2) = 75 THEN 5555
        WHEN SUBSTR(TO_CHAR(MGR),1,2) = 76 THEN 6666
        WHEN SUBSTR(TO_CHAR(MGR),1,2) = 77 THEN 7777
        WHEN SUBSTR(TO_CHAR(MGR),1,2) = 78 THEN 8888
        ELSE MGR
        END AS CHG_MGR
    FROM EMP;

SELECT SUM(SAL),COUNT(*), ROUND(AVG(SAL)) AS AVG, MIN(SAL), MAX(SAL)
    FROM EMP;

SELECT SUM(SAL), SUM(ALL SAL), SUM(DISTINCT SAL)
    FROM EMP;
    
-- 예제
SELECT COUNT(*)
    FROM EMP
    WHERE SAL>2000;
    
SELECT MAX(SAL)
    FROM EMP
    WHERE DEPTNO =10;
    
SELECT MIN(SAL)
    FROM EMP
    WHERE DEPTNO =10;

SELECT MAX(HIREDATE)
    FROM EMP
    WHERE DEPTNO =20;

SELECT MIN(HIREDATE)
    FROM EMP
    WHERE DEPTNO =20;

SELECT AVG(NVL(COMM,0))
    FROM EMP
    WHERE DEPTNO = 10;

SELECT ROUND(AVG(NVL(COMM,0)))
    FROM EMP
    WHERE DEPTNO = 30;

SELECT MAX(SAL)
    FROM EMP
    WHERE DEPTNO = 30;
    
--부서별 최대 급여는?
SELECT DEPTNO, MAX(SAL)
    FROM EMP
    GROUP BY DEPTNO
    ORDER BY DEPTNO DESC;
    
--부서&직업 조합에서 가장 많이 버는 금액    
SELECT DEPTNO, JOB, MAX(SAL)
FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;

SELECT DEPTNO, AVG(COMM)
    FROM EMP
    GROUP BY DEPTNO;
    
-- ERROR    
SELECT ENAME, DEPTNO, MAX(SAL) -- DEPTNO&MAX(SAL)로 행의 수를 4개로 맞추었으나 ENAME이 4행이 아니라 오류
    FROM EMP
    GROUP BY DEPTNO; -- GROUP BY절에 사용하지 않은 칼럼을 SELECT에 사용하면 안된다.
    
SELECT DEPTNO, AVG(SAL)
    FROM EMP
    WHERE SAL > 2000 -- 2000보다 큰 사람들것만 평균 계산
    GROUP BY DEPTNO;

SELECT DEPTNO, AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO
    HAVING AVG(SAL) > 2000; --전체에 대한 평균 계산