SELECT ENAME, SAL
    FROM EMP
    WHERE SAL IN (SELECT MAX(SAL)
        FROM EMP GROUP BY DEPTNO);

SELECT * FROM DEPT_TEMP;

CREATE TABLE DEPT_TEMP AS 
    SELECT * FROM DEPT WHERE 1 <> 1;
    
INSERT INTO DEPT_TEMP VALUES (50,'SAELES','SEOUL');
INSERT INTO DEPT_TEMP (DEPTNO, LOC) VALUES (40,'BUSAN');

INSERT INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
 (SELECT * FROM DEPT); 
 
 UPDATE DEPT_TEMP SET LOC = 'BUSAN' 
    WHERE DEPTNO = 20;
    
UPDATE DEPT_TEMP SET 
    DNAME = 'HR', LOC = 'DAEGU'
    WHERE DEPTNO = 50;
    
CREATE USER ORCLSTUDY
IDENTIFIED BY ORACLE;

GRANT INSERT ON EMP TO ORCLSTUDY;

SELECT * 
    FROM EMP E, DEPT D
WHERE E.DEPTNO = D.DEPTNO
    AND E.SAL >= 3000;
    
SELECT E.EMPNO, E.ENAME, DEPTNO, D.DNAME
    FROM EMP E NATURAL JOIN DEPT D;
    
SELECT E.EMPNO, E.ENAME, DEPTNO, D.DNAME
    FROM EMP E JOIN DEPT D USING (DEPTNO);
    
SELECT E.EMPNO, E.ENAME, E.DEPTNO, D.DNAME
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO);
    
SELECT * 
    FROM EMP E1, EMP E2
    WHERE E1.MGR = E2.EMPNO(+);
    
SELECT * 
    FROM EMP E1 LEFT OUTER JOIN EMP E2 
    ON (E1.MGR = E2.EMPNO);
    
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    WHERE SAL >= 3000
    AND JOB IS NOT NULL;

SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    WHERE SAL >= 3000
    AND JOB IS NOT NULL;
    
SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM
    FROM EMP E NATURAL JOIN DEPT D 
    WHERE SAL >= 3000
    AND JOB IS NOT NULL;

SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E NATURAL JOIN DEPT D
    WHERE SAL > 2000
ORDER BY DEPTNO;
    
SELECT E.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    WHERE SAL > 2000
ORDER BY DEPTNO;

SELECT DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.SAL
    FROM EMP E JOIN DEPT D USING(DEPTNO)
    WHERE SAL > 2000
ORDER BY DEPTNO;

SELECT E.DEPTNO, D.DNAME, TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL
, MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
    GROUP BY E.DEPTNO, D.DNAME
ORDER BY E.DEPTNO;

SELECT DEPTNO, D.DNAME, TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL
, MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
    FROM EMP E NATURAL JOIN DEPT D
    GROUP BY DEPTNO, D.DNAME
ORDER BY DEPTNO;

SELECT DEPTNO, D.DNAME, TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL
, MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
    FROM EMP E JOIN DEPT D USING (DEPTNO)
    GROUP BY DEPTNO, D.DNAME
ORDER BY DEPTNO;

SELECT E.DEPTNO, D.DNAME, TRUNC(AVG(E.SAL)) AS AVG_SAL, MAX(E.SAL) AS MAX_SAL
, MIN(E.SAL) AS MIN_SAL, COUNT(*) AS CNT
    FROM EMP E JOIN DEPT D ON (E.DEPTNO = D.DEPTNO)
    GROUP BY E.DEPTNO, D.DNAME
ORDER BY E.DEPTNO;

SELECT REGEXP_REPLACE('ABCDEFGHIJ', '([A-Z]{3})([A-Z]{3})', '\1-\2-') AS transformed_string
FROM DUAL;
                      
SELECT * FROM DEPT;