SELECT INSTR('HELLO. HELLO, HELLO!','E',2,2)
    FROM DUAL;

SELECT REPLACE ('010-1234-5678','-','/')
    FROM DUAL;
    
SELECT LPAD('ORACLE',10,'#')
    FROM DUAL;
    
--   최고 급여 받는 직원(부서별) -> 다중행 서브쿼리
SELECT * 
    FROM EMP
    WHERE SAL IN (
 SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
 
 SELECT * 
    FROM EMP
    WHERE SAL < ALL (SELECT SAL FROM EMP
        WHERE DEPTNO = 30)
    ORDER BY SAL, EMPNO;
    
SELECT * FROM EMP
    WHERE EXISTS (SELECT DNAME FROM DEPT WHERE DEPTNO = 1000);
    
-- 10번 부서에 속한 모든 사람보다 일찍 입사한 사람 정보
SELECT * 
    FROM EMP
    WHERE HIREDATE < ANY (
        SELECT HIREDATE FROM EMP WHERE DEPTNO = '10');
    
SELECT *
    FROM EMP
    WHERE (DEPTNO,SAL) IN (SELECT DEPTNO,MAX(SAL)
                FROM EMP
                GROUP BY DEPTNO);
            
SELECT * FROM EMP D,(SELECT * FROM EMP) E;

SELECT E10.ENAME, E10.ENAME, E10.DEPTNO, D.DNAME, D.LOC
    FROM(SELECT * FROM EMP WHERE DEPTNO = 10) E10,
        (SELECT * FROM DEPT) D;
/*        
SELECT EMPNO, ENAME, JOB, SAL,
    (SELECT GRADE FROM SALGRADE
        WHERE E.SAL BETWEEN LOSAL AND HISAL) AS SALGRADE */

SELECT E.JOB, E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME
    FROM EMP E, DEPT D
    WHERE E.DEPTNO = D.DEPTNO
        AND E.DEPTNO = (SELECT DEPTNO 
                    FROM EMP 
                    WHERE ENAME = 'ALLEN');

SELECT E.*, D.*, S.GRADE
    FROM EMP E, DEPT D, SALGRADE S
    WHERE E.DEPTNO = D.DEPTNO   --테이블 조인
    AND E.SAL BETWEEN S.LOSAL AND S.HISAL --테이블 조인
        AND E.SAL > (SELECT AVG(SAL) FROM EMP); -- 조건
    
SELECT *
FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO
AND E.SAL BETWEEN S.LOSAL AND S.HISAL
AND E.SAL > (SELECT AVG(SAL) FROM EMP); 
    
--테이블 복사
CREATE TABLE DEPT_TEMP AS SELECT * FROM DEPT;

--혼공 시작
UPDATE DEPT_TEMP 
    SET DNAME = 'CS/CX',
        LOC = 'BUSAN'
    WHERE DEPTNO = 50;

SELECT * FROM DEPT_TEMP
    ORDER BY DEPTNO;
    
INSERT ALL 
    INTO DEPT_TEMP VALUES (40,'RECEPTION','FRONT')
    INTO DEPT_TEMP VALUES (30,'SPA','SPA')
    INTO DEPT_TEMP VALUES (20,'GUARD','POOL')
    INTO DEPT_TEMP VALUES (10,'OPERATION','OFFICE') 
SELECT * FROM DUAL;

UPDATE DEPT_TEMP
    SET DNAME = 'LIFE_GUARD'
    WHERE LOC = 'POOL';
    
ROLLBACK;

INSERT ALL
    INTO DEPT_TEMP VALUES (60,'SLAES','INCHEON')
    INTO DEPT_TEMP VALUES (70,'DOCTOR','HOSPITAL')
SELECT * FROM DUAL;

UPDATE DEPT_TEMP
    SET DNAME = NULL
    WHERE DEPTNO = 10;
    
    ROLLBACK;
    
CREATE TABLE EMP_TEMP AS SELECT * FROM EMP;

SELECT * FROM EMP_TEMP;

UPDATE EMP_TEMP
    SET COMM = 50
    WHERE SAL <= 2500;
    
SELECT SAL, COMM FROM EMP_TEMP WHERE SAL <= 2500;

CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT; 

UPDATE DEPT_TEMP2
    SET DNAME = 'RESEARCH', LOC = 'DALLAS';
        
SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2
    SET LOC = 'SEOUL'
    WHERE DEPTNO = (
        SELECT DEPTNO FROM DEPT_TEMP2
        WHERE DNAME = 'OPERATIONS');
        
ROLLBACK;

DELETE FROM EMP_TEMP WHERE JOB='MANAGER';
SELECT * FROM EMP_TEMP;

CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TCL;

DELETE FROM DEPT_TCL
    WHERE DEPTNO = 40;
    
SELECT * FROM DEPT_TCL;

COMMIT;

UPDATE DEPT_TCL 
    SET LOC = 'SEOUL'
    WHERE DEPTNO = 30;
    
SELECT * FROM DEPT_TEMP;

CREATE TABLE DEPT_TEMP AS (SELECT * FROM DEPT WHERE 1<>1);

DROP TABLE DEPT_TEMP;

CREATE TABLE SAMPLE (
    NAME    VARCHAR2(8),
    AGE     NUMBER(3));
    
SELECT * FROM SAMPLE;

CREATE TABLE EMP_DDL(
    EMPNO   NUMBER(4),
    ENAME   VARCHAR2(10),
    JOB     VARCHAR2(9),
    MGR     NUMBER(4),
    HIREDATE    DATE,
    SAL     NUMBER(7,2),
    COMM    NUMBER(7,2),
    DEPTNO  NUMBER(2)
    );
    
SELECT * FROM EMP_DDL;

INSERT ALL
    INTO EMP_DDL VALUES (10,'A','PC','11',SYSDATE,1000,10,1)
    SELECT * FROM DUAL;
    
CREATE INDEX IDX_EMP_SAL
    ON EMP(SAL);

DROP INDEX IDX_EMP_SAL;

DROP TABLE EMP_NEW;