SELECT * FROM EMP;

--사원번호가 7934인 사람은?
SELECT * FROM EMP
WHERE EMPNO = 7934;

SELECT EMPNO, ENAME, JOB FROM EMP
WHERE EMPNO > 980;

SELECT ENAME, SAL FROM EMP
WHERE SAL*12 > 4000;

SELECT * FROM EMP
WHERE SAL > 2000 
    AND MGR > 7800;
    
SELECT * FROM EMP
WHERE SAL >=2500
     AND JOB = 'ANALYST';
     
SELECT * FROM EMP
WHERE ENAME >= 'F';

SELECT * FROM EMP
WHERE SAL != 3000;

SELECT ENAME, JOB FROM EMP
WHERE JOB  IN ('CLERK', 'SALESMAN', 'ANALYST');

SELECT ENAME, JOB FROM EMP
WHERE JOB NOT IN ('CLERK', 'SALESMAN', 'ANALYST');

SELECT * FROM EMP
WHERE DEPTNO IN(10, 20);
    
SELECT * FROM EMP
WHERE SAL > 2000 
    AND SAL < 3000;
    
SELECT * FROM EMP
WHERE SAL BETWEEN 2000 AND 3000;
    
SELECT * FROM EMP
WHERE SAL NOT BETWEEN 2000 AND 3000;

SELECT * FROM EMP
WHERE ENAME LIKE'S%';
-- 이름이 S로 시작하는

SELECT * FROM EMP
WHERE ENAME LIKE 'T%';
-- 이름이 T로 끝나는

SELECT * FROM EMP
WHERE ENAME LIKE '_C%';

-- 중간에 AM이 들어가는
SELECT * FROM EMP
WHERE ENAME LIKE'%AM%';

-- 중간에 AM이 들어가지 않는
SELECT * FROM EMP
WHERE ENAME NOT LIKE'%AM%';

--COMM의 값이 없는
SELECT * FROM EMP
WHERE COMM IS NULL;

-- COMM에 값이 없지 않는
SELECT * FROM EMP
WHERE COMM IS NOT NULL;

--SAL의 값이 있고 COMM에 값이 없는
SELECT * FROM EMP
WHERE SAL IS NOT NULL
    AND COMM IS NULL;
    
-- DEPTNO가 10이거나 20인 정보 (합집합, 중복 값 제거)
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 20;

-- DEPTNO가 10이거나 20인 정보 (칼럼 순서가 달라 값 이상함)    
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10
UNION
SELECT EMPNO, ENAME, DEPTNO, SAL
    FROM EMP
    WHERE DEPTNO = 20;

-- DEPTNO가 10이거나 20인 정보 (합집합, 중복 값 포함)
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10
UNION ALL
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 20;
    
-- 차집합
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
MINUS
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 20;
    
-- 교집합
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
INTERSECT
SELECT EMPNO, ENAME, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 20;
    
SELECT *FROM EMP
    WHERE ENAME LIKE '%S';

-- 실습
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 30 
INTERSECT
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
    WHERE JOB = 'SALESMAN';
    
-- 실습    
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
    WHERE DEPTNO = 30 AND JOB = 'SALESMAN';
--실습
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
    FROM EMP
        WHERE DEPTNO IN (20,30) 
        AND SAL > 2000;
        
-- MGR은 사원번호로 나오기 때문에 이름 확인 위한 쿼리
SELECT ENAME, MGR, HIREDATE, JOB FROM EMP
WHERE ENAME = 'SMITH';

-- DEPT 테이블 출력
SELECT * FROM DEPT;

DESC SALGRADE;

-- 중복 테이블 제거
SELECT DISTINCT DEPTNO 
    FROM EMP;

-- 별칭 만들기 / AS는 안써도 무방함
SELECT ENAME, SAL*12 AS SAL_YEAR 
    FROM EMP;

SELECT ENAME, EMPNO, DEPTNO 
    FROM EMP;

-- 부서번호 오름차
SELECT ENAME, EMPNO, DEPTNO 
    FROM EMP
    WHERE DEPTNO IN (10,20)
    ORDER BY DEPTNO;
-- 부서번호 내림차
SELECT ENAME, EMPNO, DEPTNO 
    FROM EMP
    WHERE DEPTNO IN (10,20)
    ORDER BY DEPTNO DESC;
    
-- 이름 오름차
SELECT ENAME, EMPNO, DEPTNO 
    FROM EMP
    WHERE DEPTNO IN (10,20)
    ORDER BY ENAME;

-- 이름 내름차    
SELECT ENAME, EMPNO, DEPTNO 
    FROM EMP
    WHERE DEPTNO IN (10,20)
    ORDER BY ENAME DESC;
    
SELECT * FROM EMP
    ORDER BY EMPNO;

SELECT DISTINCT JOB 
    FROM EMP;

